_BASE_: "base.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: ""
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 3
SOLVER:
  MAX_ITER: 300